Repository racklet/racklet, pull requests merged in 2021-06, with the labels that each got.

#30 Update introductory presentation link
  README.md
Labels: kind/documentation

#22 Update RFC-0001
  docs/rfcs/0001-high-level-architecture.md
Labels: kind/design

#31 RFC-0001: Add spans for referring to individual values and user goals
  docs/rfcs/0001-high-level-architecture.md
Labels: kind/documentation, subproject/org-meta

#32 RFC-0001: Fix the rendering of lists with span tag entries in mdBook
  docs/rfcs/0001-high-level-architecture.md
Labels: kind/bug, kind/documentation

#34 Add render-drawio-action for automatically rendering .drawio files
  .github/workflows/drawio-render.yml
Labels: kind/documentation, kind/organization, priority/important-soon, subproject/org-meta

#35 Update the draw.io rendering GH Action
  .github/workflows/drawio-render.yml
Labels: kind/documentation, subproject/org-meta
